### ISSUE TITLE
Not working in Tomcat9 / Lack of proper documentation to create new Print Configuration

### ISSUE THREAD

**Issue by 1Map** [mapfish/mapfish-print#1545] opened 2020-10-28 06:57 UTC
Download and installed the latest war file in Ubuntu / Tomcat9

1) Mapfish did not start up due to broken characters and blank line in: /var/lib/tomcat9/webapps/mapfish/META-INF/MANIFEST.MF
2) I also had to manually create a folder /print-apps under /var/lib/tomcat9/webapps/mapfish/

Question is:  How can now add a new Print Configuration / App under print-apps ?

If I navigate to /mapfish I only see blank dropdown for: Print App / Example

![image](https://user-images.githubusercontent.com/1152458/97402607-7abd0d00-18fb-11eb-91bd-9b5e04f96f16.png)

**Comment by sbrunner** [comment] 2020-10-28 08:44
> Question is: How can now add a new Print Configuration / App under print-apps ?

You should add your print configuration in the folder: `<tomcat home>/webapps/ROOT/print-apps`

**Comment by sbrunner** [comment] 2020-10-28 08:44
1. probably duplicate of #1540

**Comment by RussellGrew** [comment] 2020-11-27 05:36
Following on this question how can I make this work with Docker?

I `docker pull camptocamp/mapfish_print` and plumb through port 8080 fine.

I was thinking I had to associate `/usr/local/tomcat/webapps/ROOT/print-apps` with `d:\dev\mapfish-print\examples\src\test\resources\examples` where I have git cloned to `d:\dev`?

I have also tried `D:\dev\mapfish-print\examples\src\test\resources\examples\simple`

The capabilities button, and some other buttons work.

Perhaps I am missing some environment variables?

Any advice is appreciated. I very much want to explore using Mapfish print.

**Comment by sbrunner** [comment] 2020-11-27 08:36
The following commands work correctly on Linux:
```
docker run --rm -v $PWD/examples/src/test/resources/examples/:/usr/local/tomcat/webapps/ROOT/print-apps -p 8081:8080 camptocamp/mapfish_print 
```
And effectively the getcapabilities button doesn't work correctly ...

**Comment by RussellGrew** [comment] 2020-11-27 19:40
Thanks @sbrunner that works great on Ubuntu. I will test on Windows next week. 

I see the docker image was updated 17 hours ago so I will refresh.

**Closed** 2020-11-30 08:19 UTC
